-- MySQL Script generated by MySQL Workbench
-- Fri Sep  5 15:23:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prestamos_norm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prestamos_norm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prestamos_norm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `prestamos_norm` ;

-- -----------------------------------------------------
-- Table `prestamos_norm`.`borrower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`borrower` (
  `borrower_id` BIGINT NOT NULL AUTO_INCREMENT,
  `external_borrower_key` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`borrower_id`),
  UNIQUE INDEX `uq_borrower_ext` (`external_borrower_key` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_verification_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_verification_status` (
  `verification_status_id` INT NOT NULL AUTO_INCREMENT,
  `verification_status_code` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`verification_status_id`),
  UNIQUE INDEX `uq_verification_status` (`verification_status_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_purpose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_purpose` (
  `purpose_id` INT NOT NULL AUTO_INCREMENT,
  `purpose_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`purpose_id`),
  UNIQUE INDEX `uq_purpose` (`purpose_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_application_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_application_type` (
  `application_type_id` INT NOT NULL AUTO_INCREMENT,
  `application_type_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`application_type_id`),
  UNIQUE INDEX `uq_application_type` (`application_type_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_policy_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_policy_code` (
  `policy_code_id` INT NOT NULL AUTO_INCREMENT,
  `policy_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`policy_code_id`),
  UNIQUE INDEX `uq_policy_code` (`policy_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_disbursement_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_disbursement_method` (
  `disbursement_method_id` INT NOT NULL AUTO_INCREMENT,
  `disbursement_method_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`disbursement_method_id`),
  UNIQUE INDEX `uq_disbursement_method` (`disbursement_method_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_initial_list_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_initial_list_status` (
  `initial_list_status_id` INT NOT NULL AUTO_INCREMENT,
  `initial_list_status_code` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`initial_list_status_id`),
  UNIQUE INDEX `uq_initial_list_status` (`initial_list_status_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`listing` (
  `listing_id` BIGINT NOT NULL AUTO_INCREMENT,
  `initial_list_status_id` INT NULL DEFAULT NULL,
  `url` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `initial_list_status_id` (`initial_list_status_id` ASC) VISIBLE,
  CONSTRAINT `listing_ibfk_1`
    FOREIGN KEY (`initial_list_status_id`)
    REFERENCES `prestamos_norm`.`dim_initial_list_status` (`initial_list_status_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 1548552
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`application` (
  `application_id` BIGINT NOT NULL AUTO_INCREMENT,
  `borrower_id` BIGINT NOT NULL,
  `source_system_code` CHAR(1) NOT NULL,
  `external_application_key` CHAR(32) NOT NULL,
  `application_date` DATE NOT NULL,
  `verification_status_id` INT NULL DEFAULT NULL,
  `purpose_id` INT NULL DEFAULT NULL,
  `application_type_id` INT NULL DEFAULT NULL,
  `policy_code_id` INT NULL DEFAULT NULL,
  `disbursement_method_id` INT NULL DEFAULT NULL,
  `listing_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`application_id`),
  UNIQUE INDEX `uq_app_ext` (`external_application_key` ASC) VISIBLE,
  INDEX `borrower_id` (`borrower_id` ASC) VISIBLE,
  INDEX `verification_status_id` (`verification_status_id` ASC) VISIBLE,
  INDEX `purpose_id` (`purpose_id` ASC) VISIBLE,
  INDEX `application_type_id` (`application_type_id` ASC) VISIBLE,
  INDEX `policy_code_id` (`policy_code_id` ASC) VISIBLE,
  INDEX `disbursement_method_id` (`disbursement_method_id` ASC) VISIBLE,
  INDEX `listing_id` (`listing_id` ASC) VISIBLE,
  INDEX `idx_app_date` (`application_date` ASC) VISIBLE,
  INDEX `idx_app_ext` (`external_application_key` ASC) VISIBLE,
  CONSTRAINT `application_ibfk_1`
    FOREIGN KEY (`borrower_id`)
    REFERENCES `prestamos_norm`.`borrower` (`borrower_id`),
  CONSTRAINT `application_ibfk_2`
    FOREIGN KEY (`verification_status_id`)
    REFERENCES `prestamos_norm`.`dim_verification_status` (`verification_status_id`),
  CONSTRAINT `application_ibfk_3`
    FOREIGN KEY (`purpose_id`)
    REFERENCES `prestamos_norm`.`dim_purpose` (`purpose_id`),
  CONSTRAINT `application_ibfk_4`
    FOREIGN KEY (`application_type_id`)
    REFERENCES `prestamos_norm`.`dim_application_type` (`application_type_id`),
  CONSTRAINT `application_ibfk_5`
    FOREIGN KEY (`policy_code_id`)
    REFERENCES `prestamos_norm`.`dim_policy_code` (`policy_code_id`),
  CONSTRAINT `application_ibfk_6`
    FOREIGN KEY (`disbursement_method_id`)
    REFERENCES `prestamos_norm`.`dim_disbursement_method` (`disbursement_method_id`),
  CONSTRAINT `application_ibfk_7`
    FOREIGN KEY (`listing_id`)
    REFERENCES `prestamos_norm`.`listing` (`listing_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 526652
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Solicitud normalizada (clave externa_application_key del CSV)';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`applicant_financials_snapshot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`applicant_financials_snapshot` (
  `application_id` BIGINT NOT NULL,
  `annual_inc` DECIMAL(14,2) NULL DEFAULT NULL,
  `annual_inc_joint` DECIMAL(14,2) NULL DEFAULT NULL,
  `dti` DECIMAL(6,2) NULL DEFAULT NULL,
  `dti_joint` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`application_id`),
  UNIQUE INDEX `uq_app_fin` (`application_id` ASC) VISIBLE,
  CONSTRAINT `applicant_financials_snapshot_ibfk_1`
    FOREIGN KEY (`application_id`)
    REFERENCES `prestamos_norm`.`application` (`application_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_state` (
  `state_id` INT NOT NULL AUTO_INCREMENT,
  `state_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`state_id`),
  UNIQUE INDEX `uq_state` (`state_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 116
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_zip3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_zip3` (
  `zip3_id` INT NOT NULL AUTO_INCREMENT,
  `zip3` CHAR(3) NOT NULL,
  PRIMARY KEY (`zip3_id`),
  UNIQUE INDEX `uq_zip3` (`zip3` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1941
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`application_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`application_address` (
  `application_id` BIGINT NOT NULL,
  `state_id` INT NULL DEFAULT NULL,
  `zip3_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`application_id`),
  UNIQUE INDEX `uq_app_addr` (`application_id` ASC) VISIBLE,
  INDEX `state_id` (`state_id` ASC) VISIBLE,
  INDEX `zip3_id` (`zip3_id` ASC) VISIBLE,
  CONSTRAINT `application_address_ibfk_1`
    FOREIGN KEY (`application_id`)
    REFERENCES `prestamos_norm`.`application` (`application_id`)
    ON DELETE CASCADE,
  CONSTRAINT `application_address_ibfk_2`
    FOREIGN KEY (`state_id`)
    REFERENCES `prestamos_norm`.`dim_state` (`state_id`),
  CONSTRAINT `application_address_ibfk_3`
    FOREIGN KEY (`zip3_id`)
    REFERENCES `prestamos_norm`.`dim_zip3` (`zip3_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Ubicación del solicitante (state, zip3)';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`credit_history_snapshot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`credit_history_snapshot` (
  `application_id` BIGINT NOT NULL,
  `earliest_cr_line` DATE NULL DEFAULT NULL,
  `last_credit_pull_d` DATE NULL DEFAULT NULL,
  `inq_last_6mths` SMALLINT NULL DEFAULT NULL,
  `delinq_2yrs` SMALLINT NULL DEFAULT NULL,
  `mths_since_last_delinq` SMALLINT NULL DEFAULT NULL,
  `mths_since_last_record` SMALLINT NULL DEFAULT NULL,
  `mths_since_recent_inq` SMALLINT NULL DEFAULT NULL,
  `pub_rec` SMALLINT NULL DEFAULT NULL,
  `total_acc` SMALLINT NULL DEFAULT NULL,
  `open_acc` SMALLINT NULL DEFAULT NULL,
  `revol_bal` INT NULL DEFAULT NULL,
  `revol_util` DECIMAL(6,1) NULL DEFAULT NULL,
  PRIMARY KEY (`application_id`),
  UNIQUE INDEX `uq_app_ch` (`application_id` ASC) VISIBLE,
  CONSTRAINT `credit_history_snapshot_ibfk_1`
    FOREIGN KEY (`application_id`)
    REFERENCES `prestamos_norm`.`application` (`application_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Foto del historial crediticio (revolving, inquiries, etc.)';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_emp_length`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_emp_length` (
  `emp_length_id` INT NOT NULL AUTO_INCREMENT,
  `years` TINYINT NULL DEFAULT NULL,
  `original_text` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`emp_length_id`),
  UNIQUE INDEX `uq_emp_length` (`original_text` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_emp_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_emp_title` (
  `emp_title_id` INT NOT NULL AUTO_INCREMENT,
  `emp_title` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`emp_title_id`),
  UNIQUE INDEX `uq_emp_title` (`emp_title` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 239194
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_grade` (
  `grade_id` INT NOT NULL AUTO_INCREMENT,
  `grade_code` CHAR(1) NOT NULL,
  PRIMARY KEY (`grade_id`),
  UNIQUE INDEX `uq_grade_code` (`grade_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_hardship_loan_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_hardship_loan_status` (
  `hardship_loan_status_id` INT NOT NULL AUTO_INCREMENT,
  `hardship_loan_status_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`hardship_loan_status_id`),
  UNIQUE INDEX `uq_hardship_loan_status` (`hardship_loan_status_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_hardship_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_hardship_status` (
  `hardship_status_id` INT NOT NULL AUTO_INCREMENT,
  `hardship_status_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`hardship_status_id`),
  UNIQUE INDEX `uq_hardship_status` (`hardship_status_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_hardship_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_hardship_type` (
  `hardship_type_id` INT NOT NULL AUTO_INCREMENT,
  `hardship_type_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`hardship_type_id`),
  UNIQUE INDEX `uq_hardship_type` (`hardship_type_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_home_ownership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_home_ownership` (
  `home_ownership_id` INT NOT NULL AUTO_INCREMENT,
  `home_ownership_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`home_ownership_id`),
  UNIQUE INDEX `uq_home_ownership` (`home_ownership_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_loan_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_loan_status` (
  `loan_status_id` INT NOT NULL AUTO_INCREMENT,
  `loan_status_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`loan_status_id`),
  UNIQUE INDEX `uq_loan_status` (`loan_status_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_settlement_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_settlement_status` (
  `settlement_status_id` INT NOT NULL AUTO_INCREMENT,
  `settlement_status_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`settlement_status_id`),
  UNIQUE INDEX `uq_settlement_status` (`settlement_status_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_sub_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_sub_grade` (
  `sub_grade_id` INT NOT NULL AUTO_INCREMENT,
  `sub_grade_code` CHAR(2) NOT NULL,
  `grade_id` INT NOT NULL,
  PRIMARY KEY (`sub_grade_id`),
  UNIQUE INDEX `uq_sub_grade_code` (`sub_grade_code` ASC) VISIBLE,
  INDEX `fk_sub_grade_grade` (`grade_id` ASC) VISIBLE,
  CONSTRAINT `fk_sub_grade_grade`
    FOREIGN KEY (`grade_id`)
    REFERENCES `prestamos_norm`.`dim_grade` (`grade_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`dim_term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`dim_term` (
  `term_id` INT NOT NULL AUTO_INCREMENT,
  `term_months` TINYINT NOT NULL,
  PRIMARY KEY (`term_id`),
  UNIQUE INDEX `uq_term_months` (`term_months` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`employment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`employment` (
  `application_id` BIGINT NOT NULL,
  `emp_title_id` INT NULL DEFAULT NULL,
  `emp_length_id` INT NULL DEFAULT NULL,
  `home_ownership_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`application_id`),
  UNIQUE INDEX `uq_app_emp` (`application_id` ASC) VISIBLE,
  INDEX `emp_title_id` (`emp_title_id` ASC) VISIBLE,
  INDEX `emp_length_id` (`emp_length_id` ASC) VISIBLE,
  INDEX `home_ownership_id` (`home_ownership_id` ASC) VISIBLE,
  CONSTRAINT `employment_ibfk_1`
    FOREIGN KEY (`application_id`)
    REFERENCES `prestamos_norm`.`application` (`application_id`)
    ON DELETE CASCADE,
  CONSTRAINT `employment_ibfk_2`
    FOREIGN KEY (`emp_title_id`)
    REFERENCES `prestamos_norm`.`dim_emp_title` (`emp_title_id`),
  CONSTRAINT `employment_ibfk_3`
    FOREIGN KEY (`emp_length_id`)
    REFERENCES `prestamos_norm`.`dim_emp_length` (`emp_length_id`),
  CONSTRAINT `employment_ibfk_4`
    FOREIGN KEY (`home_ownership_id`)
    REFERENCES `prestamos_norm`.`dim_home_ownership` (`home_ownership_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Empleo declarado del solicitante';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`loan` (
  `loan_id` BIGINT NOT NULL,
  `application_id` BIGINT NOT NULL,
  `decision_id` BIGINT NULL DEFAULT NULL,
  `decision_date` DATE NULL DEFAULT NULL,
  `loan_status_id` INT NULL DEFAULT NULL,
  `sub_grade_id` INT NULL DEFAULT NULL,
  `grade_id` INT NULL DEFAULT NULL,
  `term_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `application_id` (`application_id` ASC) VISIBLE,
  INDEX `sub_grade_id` (`sub_grade_id` ASC) VISIBLE,
  INDEX `grade_id` (`grade_id` ASC) VISIBLE,
  INDEX `idx_loan_status` (`loan_status_id` ASC) VISIBLE,
  INDEX `idx_loan_term` (`term_id` ASC) VISIBLE,
  CONSTRAINT `loan_ibfk_1`
    FOREIGN KEY (`application_id`)
    REFERENCES `prestamos_norm`.`application` (`application_id`),
  CONSTRAINT `loan_ibfk_2`
    FOREIGN KEY (`loan_status_id`)
    REFERENCES `prestamos_norm`.`dim_loan_status` (`loan_status_id`),
  CONSTRAINT `loan_ibfk_3`
    FOREIGN KEY (`sub_grade_id`)
    REFERENCES `prestamos_norm`.`dim_sub_grade` (`sub_grade_id`),
  CONSTRAINT `loan_ibfk_4`
    FOREIGN KEY (`grade_id`)
    REFERENCES `prestamos_norm`.`dim_grade` (`grade_id`),
  CONSTRAINT `loan_ibfk_5`
    FOREIGN KEY (`term_id`)
    REFERENCES `prestamos_norm`.`dim_term` (`term_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Préstamo: relaciona application + status + grade/term';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`hardship_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`hardship_case` (
  `loan_id` BIGINT NOT NULL,
  `hardship_type_id` INT NULL DEFAULT NULL,
  `hardship_status_id` INT NULL DEFAULT NULL,
  `hardship_loan_status_id` INT NULL DEFAULT NULL,
  `hardship_amount` DECIMAL(14,2) NULL DEFAULT NULL,
  `hardship_start_date` DATE NULL DEFAULT NULL,
  `hardship_end_date` DATE NULL DEFAULT NULL,
  `payment_plan_start_date` DATE NULL DEFAULT NULL,
  `deferral_term` SMALLINT NULL DEFAULT NULL,
  `hardship_length` SMALLINT NULL DEFAULT NULL,
  `hardship_dpd` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `hardship_type_id` (`hardship_type_id` ASC) VISIBLE,
  INDEX `hardship_status_id` (`hardship_status_id` ASC) VISIBLE,
  INDEX `hardship_loan_status_id` (`hardship_loan_status_id` ASC) VISIBLE,
  CONSTRAINT `hardship_case_ibfk_1`
    FOREIGN KEY (`loan_id`)
    REFERENCES `prestamos_norm`.`loan` (`loan_id`)
    ON DELETE CASCADE,
  CONSTRAINT `hardship_case_ibfk_2`
    FOREIGN KEY (`hardship_type_id`)
    REFERENCES `prestamos_norm`.`dim_hardship_type` (`hardship_type_id`),
  CONSTRAINT `hardship_case_ibfk_3`
    FOREIGN KEY (`hardship_status_id`)
    REFERENCES `prestamos_norm`.`dim_hardship_status` (`hardship_status_id`),
  CONSTRAINT `hardship_case_ibfk_4`
    FOREIGN KEY (`hardship_loan_status_id`)
    REFERENCES `prestamos_norm`.`dim_hardship_loan_status` (`hardship_loan_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prestamos_norm`.`loan_terms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`loan_terms` (
  `loan_id` BIGINT NOT NULL,
  `requested_amount` INT NULL DEFAULT NULL,
  `funded_amount` INT NULL DEFAULT NULL,
  `funded_amount_inv` INT NULL DEFAULT NULL,
  `installment` DECIMAL(14,2) NULL DEFAULT NULL,
  `int_rate` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`),
  UNIQUE INDEX `uq_loan_lt` (`loan_id` ASC) VISIBLE,
  INDEX `idx_terms_rate` (`int_rate` ASC) VISIBLE,
  INDEX `idx_terms_amounts` (`requested_amount` ASC, `funded_amount` ASC) VISIBLE,
  CONSTRAINT `loan_terms_ibfk_1`
    FOREIGN KEY (`loan_id`)
    REFERENCES `prestamos_norm`.`loan` (`loan_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Condiciones financieras del préstamo (tasa, montos, cuota)';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`payment_status_snapshot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`payment_status_snapshot` (
  `loan_id` BIGINT NOT NULL,
  `last_pymnt_d` DATE NULL DEFAULT NULL,
  `next_pymnt_d` DATE NULL DEFAULT NULL,
  `last_pymnt_amnt` DECIMAL(14,2) NULL DEFAULT NULL,
  `total_pymnt` DECIMAL(16,2) NULL DEFAULT NULL,
  `total_pymnt_inv` DECIMAL(16,2) NULL DEFAULT NULL,
  `total_rec_prncp` DECIMAL(16,2) NULL DEFAULT NULL,
  `total_rec_int` DECIMAL(16,2) NULL DEFAULT NULL,
  `total_rec_late_fee` DECIMAL(14,2) NULL DEFAULT NULL,
  `recoveries` DECIMAL(14,2) NULL DEFAULT NULL,
  `collection_recovery_fee` DECIMAL(14,2) NULL DEFAULT NULL,
  `out_prncp` DECIMAL(16,2) NULL DEFAULT NULL,
  `out_prncp_inv` DECIMAL(16,2) NULL DEFAULT NULL,
  `pymnt_plan` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`),
  UNIQUE INDEX `uq_loan_ps` (`loan_id` ASC) VISIBLE,
  INDEX `idx_pay_last_dt` (`last_pymnt_d` ASC) VISIBLE,
  INDEX `idx_pay_next_dt` (`next_pymnt_d` ASC) VISIBLE,
  CONSTRAINT `payment_status_snapshot_ibfk_1`
    FOREIGN KEY (`loan_id`)
    REFERENCES `prestamos_norm`.`loan` (`loan_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Estado de pago a la fecha de la exportación';


-- -----------------------------------------------------
-- Table `prestamos_norm`.`settlement_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_norm`.`settlement_case` (
  `loan_id` BIGINT NOT NULL,
  `settlement_status_id` INT NULL DEFAULT NULL,
  `debt_settlement_flag` TINYINT NULL DEFAULT NULL,
  `debt_settlement_flag_date` DATE NULL DEFAULT NULL,
  `settlement_amount` DECIMAL(14,2) NULL DEFAULT NULL,
  `settlement_date` DATE NULL DEFAULT NULL,
  `settlement_percentage` DECIMAL(6,2) NULL DEFAULT NULL,
  `settlement_term` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `settlement_status_id` (`settlement_status_id` ASC) VISIBLE,
  CONSTRAINT `settlement_case_ibfk_1`
    FOREIGN KEY (`loan_id`)
    REFERENCES `prestamos_norm`.`loan` (`loan_id`)
    ON DELETE CASCADE,
  CONSTRAINT `settlement_case_ibfk_2`
    FOREIGN KEY (`settlement_status_id`)
    REFERENCES `prestamos_norm`.`dim_settlement_status` (`settlement_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
